### ISSUE TITLE
latest android sdk

### ISSUE THREAD

**Issue by cikai** [yisuren/werewolf#1]
https://developer.android.com/studio/index.html

SDK官网最最下边有，哈哈 自备梯子

Windows: [android-sdk_r24.4.1-windows.zip](https://dl.google.com/android/android-sdk_r24.4.1-windows.zip)

Linux: [android-sdk_r24.4.1-linux.tgz](https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz)

### Leader项目，永远点赞! :+1::+1::+1:

**Comment by yisuren** [comment]
谢谢慈凯。已经更新到readme中了。
我自己，找半天都没找到，呵呵。。。
你们玩不玩儿狼人杀，挺有意思的。
对这个有兴趣的话，幻影提交代码哦。
